return {
  "backdround/global-note.nvim",
  filename = "global.md",
  directory = "~/notes/",

  additional_presets = {
    projects = {
      filename = "projects-to-do.md",
      title = "List of projects",
      command_name = "ProjectsNote",
      -- All not specified options are used from the root.
    },

    food = {
      filename = "want-to-eat.md",
      title = "List of food",
      command_name = "FoodNote",
      -- All not specified options are used from the root.
    },
  },

-- Functions to toggle notes:
--  function()
--    toggle_note()
--    require("global-note").toggle_note("projects")
--    require("global-note").toggle_note("food")
--    end,
--  vim.keymap.set("n", "<leader>n", global_note.toggle_note, {
--    desc = "Toggle global note",
--})
}
-- Commands to toggle notes (they are generated by command_name field):
-- :GlobalNote -- by default
-- :ProjectsNote
-- :FoodNote
